// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Location struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Address   string `json:"address"`
	VisitedAt string `json:"visited_at"`
}

type NewLocation struct {
	Name      string `json:"name"`
	Address   string `json:"address"`
	VisitedAt string `json:"visited_at"`
}
